kind: live
title: Test

defaults:
  preset: cpu-small
  life_span: 1h

volumes:
  data:
    remote: "storage:"
    mount: /project/data
    local: data
  code:
    remote: "storage:"
    mount: /project/modules
    local: modules
  config:
    remote: "storage:"
    mount: /project/config
    local: config
  notebooks:
    remote: "storage:"
    mount: /project/notebooks
    local: notebooks
  results:
    remote: "storage:"
    mount: /project/results
    local: results
  project:
    remote: "storage:"
    mount: /project
    local: .

jobs:
  vscode:
    action: gh:apolo-actions/vscode@master
    args:
      image: ghcr.io/neuro-inc/base:latest
      job_name: vscode
      http_auth: False
      volumes_data_remote: $[[ volumes.data.remote ]]
      volumes_code_remote: $[[ volumes.code.remote ]]
      volumes_config_remote: $[[ volumes.config.remote ]]
      volumes_notebooks_remote: $[[ volumes.notebooks.remote ]]
      volumes_results_remote: $[[ volumes.results.remote ]]
